countries:
  - name: CMR
    shapefile: cmr_district_sante_2022.geojson # shapefile name in geojson format where the zonal stats bases on
    days-to-observe: 14  # number of most recent days to observe rainfall
    alert-on-threshold: 50  # threshold to send to EspoCRM
    destination-entity: CClimaticHazard